var customPresets = {
    "stacks": {
        "column": 22,
        "row": 8,
        "tracking": 4,
        "lineSpace": 12,
        "typeX": 20,
        "typeY": 18,
        "speed": -3,
        "xOffset": 5.1,
        "yOffset": 59.1,
        "yWave": 100,
        "yWavezRot": 35,
        "yWavexStr": 7,
        "fullText": true
    },
    "bricks": {
        "column": 20,
        "row": 9,
        "tracking": 17,
        "lineSpace": 7,
        "typeX": 13,
        "typeY": 20,
        "speed": -4,
        "xWave": 86,
        "xStrechWave": 25,
        "xStrechWaveChecked": 1.5708, // PI/2
        "fullText": true,
        "color1": "#ffffff",
        "bkgdColor": "#000000",
        "inpNumber": 1
    },
    "simple_z": {
        "column": 28,
        "row": 15,
        "tracking": 5,
        "lineSpace": 5,
        "typeX": 20,
        "typeY": 40,
        "speed": -4,
        "xOffset": 9.1,
        "zWave": 90,
        "xRotCamera": 33,
        "yRotCamera": -27,
        "zRotCamera": 24,
        "fullText": true
    },
    "complex_z": {
        "column": 38,
        "row": 10,
        "tracking": 5,
        "lineSpace": 6,
        "typeX": 8,
        "typeY": 21,
        "typeStroke": 0.9,
        "speed": 2,
        "xOffset": 4.1,
        "yOffset": 3.1,
        "zWave": 41,
        "xWave": 63,
        "yWave": 25,
        "yWavezRot": 22,
        "xRotCamera": 26,
        "yRotCamera": -39,
        "zRotCamera": 15,
        "zoomCamera": 200,
        "yWaveChecked": 3.1416, // PI
        "fullText": true,
        "color1": "#ffffff",
        "bkgdColor": "#000000",
        "inpNumber": 1
    },
    "zebra": {
        "column": 50,
        "row": 8,
        "tracking": 7,
        "lineSpace": 18.5,
        "typeX": 6,
        "typeY": 20,
        "typeStroke": 1.0,
        "speed": -4,
        "xOffset": 6.1,
        "yOffset": 5.1,
        "yWave": 33,
        "yWavezRot": 18,
        "yStrechWave": 35,
        "fullText": true
    },
    "harlequin": {
        "column": 40,
        "row": 7,
        "tracking": 5,
        "lineSpace": 11,
        "typeX": 9,
        "typeY": 19,
        "typeStroke": 1.1,
        "speed": 2,
        "xOffset": 2.1,
        "yOffset": 59.1,
        "yStrechWave": 58,
        "fullText": true,
        "color1": "#ffffff",
        "bkgdColor": "#000000",
        "inpNumber": 1
    }
};
