var customPresets = {
    "default": {
        "text": "THE\nMEANING\nOF ALL\nMOTIONS\nSHAPES &\nSOUNDS",
        "fontSel": 0,
        "textScale": 1,
        "vesselSW": 2,
        "crestType": 1,
        "stageAdirect": 2,
        "stageAstrength": 3,
        "stageBdirect": 2,
        "stageBstrength": 3,
        "stageA": 30,
        "stageB": 45,
        "charDelay": -2,
        "lineDelay": -3,
        "foreColor": "#ffffff",
        "bkgdColor": "#000000"
    },
    "bold_blue": {
        "text": "WHEN\nPROBABILITY\nWAVES\nCOLLAPSE\nINTO\nEVENT",
        "fontSel": 3,
        "textScale": 0.8,
        "vesselSW": 5,
        "crestType": 1,
        "stageAdirect": 1,
        "stageAstrength": 2,
        "stageBdirect": 1,
        "stageBstrength": 2,
        "stageA": 40,
        "stageB": 60,
        "charDelay": -4,
        "lineDelay": -6,
        "foreColor": "#00bfff",
        "bkgdColor": "#000000"
    },
    "filled_pink": {
        "text": "GOOD\nNIGHT\nNOISES\nEVERY\nWHERE",
        "fontSel": 1,
        "textScale": 1.2,
        "vesselSW": 0,
        "crestType": 2,
        "stageAdirect": 2,
        "stageAstrength": 3,
        "stageBdirect": 2,
        "stageBstrength": 3,
        "stageA": 25,
        "stageB": 40,
        "charDelay": -1,
        "lineDelay": -2,
        "foreColor": "#f24b78",
        "bkgdColor": "#ffffff"
    }
};
