var customPresets = {
    "speed_racer": {
        "stackCount": 14,
        "fontSize": 90,
        "innerH": 985,
        "innerV": -225,
        "rotateFactor": -0.11,
        "textColor": "#000000",
        "blockColor": "#ffffff",
        "strokeColor": "#FF7E79",
        "bkgdColor": "#0000ff",
        "text": "GO, SPEED RACER, GO! ",
        "fontSelect": 1
    },
    "to_space": {
        "stackCount": 14,
        "fontSize": 300,
        "innerH": -10,
        "innerV": -10,
        "rotateFactor": -0.28,
        "textColor": "#000000",
        "blockColor": "#ffffff",
        "strokeColor": "#000000",
        "bkgdColor": "#0000ff",
        "text": "Go. Go. Go. ",
        "fontSelect": 4
    },
    "hangul_sample": {
        "stackCount": 16,
        "fontSize": 155,
        "innerH": 140,
        "innerV": 40,
        "rotateFactor": -0.78,
        "textColor": "#FFD479",
        "blockColor": "#000000",
        "strokeColor": "#ffffff",
        "bkgdColor": "#ffffff",
        "text": "나선형의 것 ",
        "fontSelect": 5
    },
    "lost_time": {
        "stackCount": 14,
        "fontSize": 100,
        "innerH": 600,
        "innerV": 50,
        "rotateFactor": 0,
        "textColor": "#ffffff",
        "blockColor": "#000000",
        "strokeColor": "#FF7E79",
        "bkgdColor": "#FF7E79",
        "text": "LOST TIME LOST TIME ",
        "fontSelect": 3
    },
    "dot_spiral": {
        "stackCount": 20,
        "fontSize": 250,
        "innerH": -50,
        "innerV": -165,
        "rotateFactor": 0.42,
        "textColor": "#ffffff",
        "blockColor": "#000000",
        "strokeColor": "#000000",
        "bkgdColor": "#0000ff",
        "text": ". . . . . . . . ",
        "fontSelect": 4,
        "radioVal": 2
    },
    "be_aggressive": {
        "stackCount": 20,
        "fontSize": 110,
        "innerH": -150,
        "innerV": -250,
        "rotateFactor": -0.1,
        "textColor": "#FF7E79",
        "blockColor": "#000000",
        "strokeColor": "#000000",
        "bkgdColor": "#ffffff",
        "text": "BE AGGRESSIVE.  ",
        "fontSelect": 6,
        "radioVal": 2
    },
    "meat_space": {
        "stackCount": 20,
        "fontSize": 100,
        "innerH": 415,
        "innerV": 1035,
        "rotateFactor": 0,
        "textColor": "#73FA79",
        "blockColor": "#000000",
        "strokeColor": "#ffffff",
        "bkgdColor": "#ffffff",
        "text": "MEAT SPACE -- // MEAT SPACE -- //",
        "fontSelect": 2
    }
};
